# Generated by Django 5.2.4 on 2025-07-27 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='studentModel',
        ),
    ]
