# Generated by Django 5.2.3 on 2025-06-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Cover_Photo',
            field=models.ImageField(null=True, upload_to='Media/Cover_Photo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='BookCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='PublishDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
