# Generated by Django 5.2.5 on 2025-08-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Author', 'Author')], default='Author', max_length=20, null=True),
        ),
    ]
