# Generated by Django 5.2.5 on 2025-08-23 03:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_categorymodel_newsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
