# Generated by Django 5.2.5 on 2025-08-23 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_alter_newsmodel_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
