# Generated by Django 5.2.5 on 2025-08-22 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_activitylogmodel_noticemodel'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='model_name',
        ),
        migrations.AddField(
            model_name='activitylogmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='activitylogmodel',
            name='extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Viewed'), ('approve', 'Approved'), ('reject', 'Rejected')], max_length=15),
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='object_repr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
