# Generated by Django 5.2.5 on 2025-08-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0006_remove_activitylogmodel_model_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('view', 'Viewed')], max_length=15),
        ),
    ]
