# Generated by Django 5.2.5 on 2025-08-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_remove_activitylogmodel_extra_info_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylogmodel',
            options={},
        ),
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='activitylogmodel',
            name='object_id',
        ),
        migrations.AddField(
            model_name='activitylogmodel',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylogmodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='action',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='object_repr',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='activitylogmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
