# Generated by Django 5.2.5 on 2025-08-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0008_alter_activitylogmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.departmentmodel')),
                ('designation_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_from', to='adminApp.designationmodel')),
                ('designation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designation_to', to='adminApp.designationmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='adminApp.profilemodel')),
            ],
            options={
                'ordering': ['-promotion_date'],
            },
        ),
    ]
