# Generated by Django 5.2.5 on 2025-08-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0010_resignationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('Misconduct', 'Misconduct'), ('Performance', 'Performance'), ('Other', 'Other')], max_length=50)),
                ('termination_date', models.DateField()),
                ('notice_date', models.DateField()),
                ('reason', models.TextField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminApp.departmentmodel')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.profilemodel')),
            ],
        ),
    ]
