# Generated by Django 5.2.5 on 2025-08-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0012_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogmodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
