# Generated by Django 5.2.5 on 2025-08-26 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0013_activitylogmodel_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resignationmodel',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resignation_actioned', to='adminApp.profilemodel'),
        ),
        migrations.AddField(
            model_name='resignationmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
