# Generated by Django 5.2.1 on 2025-05-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('director', models.CharField(max_length=50)),
            ],
        ),
    ]
