# Generated by Django 5.2.3 on 2025-07-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0002_productmodel_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="fullName",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
