# Generated by Django 5.2.3 on 2025-06-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100)),
                ('profilePicture', models.ImageField(upload_to='media/photo')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('summary', models.TextField()),
                ('degree', models.CharField(max_length=50)),
                ('instituteName', models.CharField(max_length=50)),
                ('yearsOfGraduation', models.IntegerField()),
                ('companyName', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('yearsOfExperience', models.IntegerField()),
                ('skills', models.TextField()),
                ('hobbies', models.TextField()),
                ('achievements', models.TextField()),
            ],
        ),
    ]
