# Generated by Django 5.2.3 on 2025-07-02 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0003_customusermodel_fullname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customusermodel",
            old_name="fullName",
            new_name="studentName",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="dateOfBirth",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="profileImg",
        ),
        migrations.RemoveField(
            model_name="customusermodel",
            name="userType",
        ),
        migrations.AddField(
            model_name="customusermodel",
            name="studentId",
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="projectModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("projectName", models.CharField(max_length=100, null=True)),
                ("projectDescription", models.TextField(null=True)),
                (
                    "projectStatus",
                    models.CharField(
                        choices=[
                            ("NotStarted", "Not Started"),
                            ("InProgress", "In Progress"),
                            ("Completed", "Completed"),
                        ],
                        default="NotStarted",
                        max_length=20,
                    ),
                ),
                ("createdBy", models.CharField(max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ProductModel",
        ),
    ]
