# Generated by Django 5.2.5 on 2025-08-19 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0005_activitylogmodel_noticemodel'),
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequestmodel',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequestmodel',
            name='actioned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_actioned_by', to='adminApp.profilemodel'),
        ),
        migrations.AddField(
            model_name='leaverequestmodel',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('casual', 'Casual Leave')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestmodel',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='adminApp.profilemodel'),
        ),
        migrations.AlterField(
            model_name='leaverequestmodel',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestmodel',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestmodel',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='leaverequestmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
