# Generated by Django 5.2.5 on 2025-08-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0003_teammodel_teammembermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembermodel',
            name='role',
            field=models.CharField(choices=[('Lead', 'Lead'), ('Member', 'Member')], default='Member', max_length=20),
        ),
    ]
