# Generated by Django 3.2.25 on 2025-06-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_taskmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inprogress', 'Inprogress'), ('completed', 'Completed')], max_length=10, null=True),
        ),
    ]
