# Generated by Django 5.2.4 on 2025-07-19 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employerApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='candidateProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('candidateUser', models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobApplicatonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastEducation', models.CharField(max_length=100, null=True)),
                ('workExperience', models.CharField(max_length=100, null=True)),
                ('status', models.TextField(null=True)),
                ('appliedAt', models.DateField(auto_now_add=True, null=True)),
                ('candidate', models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidateApp.candidateprofilemodel')),
                ('job', models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='employerApp.jobmodel')),
            ],
        ),
    ]
