# Generated by Django 5.2.4 on 2025-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('isbn', models.CharField(max_length=100, null=True)),
                ('coverImage', models.ImageField(null=True, upload_to='media/photo')),
                ('publishedDate', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
