# Generated by Django 5.2.4 on 2025-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_studentpendingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student'), ('StudentPending', 'StudentPending')], max_length=100, null=True),
        ),
    ]
