# Generated by Django 5.2.4 on 2025-07-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_customuser_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpendingmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='studentpendingmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentpendingmodel',
            name='userType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentpendingmodel',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
