# Generated by Django 5.2.4 on 2025-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_remove_studentpendingmodel_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentpendingmodel',
            name='userType',
            field=models.CharField(choices=[('Student', 'Student')], max_length=100, null=True),
        ),
    ]
