# Generated by Django 5.2.4 on 2025-07-19 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidate_app', '0001_initial'),
        ('employer_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofilemodel',
            name='candidate_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_name', to='candidate_app.candidateprofilemodel'),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_title', to='employer_app.jobmodel'),
        ),
    ]
