# Generated by Django 5.2.3 on 2025-06-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=100)),
                ('Description', models.TextField(max_length=100)),
                ('Ingredients', models.TextField(max_length=100)),
                ('Instructions', models.TextField(max_length=100)),
                ('Image', models.ImageField(upload_to='Media/Photo')),
            ],
        ),
    ]
