# Generated by Django 5.2.4 on 2025-07-25 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('requirements', models.TextField(null=True)),
                ('salary', models.IntegerField(null=True)),
                ('jobType', models.CharField(choices=[('FullTime', 'Full Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
                ('postedDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobSeekersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('adress', models.TextField(null=True)),
                ('dateOfBirth', models.DateField(null=True)),
                ('candidateUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected')], max_length=100, null=True)),
                ('appliedAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.jobmodel')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.jobseekersmodel')),
            ],
        ),
        migrations.CreateModel(
            name='recruitersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('aboutConpany', models.TextField(null=True)),
                ('conpanyLogo', models.ImageField(null=True, upload_to='static/img/logo')),
                ('location', models.TextField(null=True)),
                ('employerUser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.recruitersmodel'),
        ),
    ]
