# Generated by Django 5.2.4 on 2025-07-19 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('aboutCompany', models.CharField(max_length=100, null=True)),
                ('companyLogo', models.ImageField(null=True, upload_to='media/photo')),
                ('location', models.CharField(max_length=100, null=True)),
                ('employerUser', models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TimeField(null=True)),
                ('description', models.TextField(null=True)),
                ('salary', models.PositiveIntegerField(null=True)),
                ('jobType', models.CharField(max_length=100, null=True)),
                ('deadline', models.DateField(null=True)),
                ('postedDate', models.DateField(auto_now_add=True, null=True)),
                ('employer', models.OneToOneField(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='employerApp.employerprofilemodel')),
            ],
        ),
    ]
