# Generated by Django 5.2.4 on 2025-07-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100, null=True)),
                ('addressName', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(null=True)),
                ('registerDate', models.DateField(null=True)),
            ],
        ),
    ]
