# Generated by Django 5.2.4 on 2025-07-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_rename_student_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='registerDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
