# Generated by Django 5.2.6 on 2025-09-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_twomodel_onemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onemodel',
            name='cunt',
            field=models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Three', 'Three')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='onemodel',
            name='itemName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='onemodel',
            name='totalItems',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twomodel',
            name='companyName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='twomodel',
            name='joiningDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='twomodel',
            name='totalItems',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
