# Generated by Django 5.2.6 on 2025-09-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_onemodel_cunt_alter_onemodel_itemname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100, null=True)),
                ('studentBio', models.TextField(null=True)),
                ('studentAge', models.IntegerField(null=True)),
                ('studentImage', models.ImageField(upload_to='static/img/student')),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updateAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
