# Generated by Django 5.2.1 on 2025-08-20 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_alter_package_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiderequestmodel',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='guiderequestmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
