# Generated by Django 5.2.1 on 2025-08-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0007_alter_guiderequestmodel_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='catalog_image',
            field=models.ImageField(blank=True, null=True, upload_to='city_images/'),
        ),
        migrations.AddField(
            model_name='country',
            name='catalog_image',
            field=models.ImageField(blank=True, null=True, upload_to='country_images/'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='driving_license_photos/'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='nid',
            field=models.ImageField(blank=True, null=True, upload_to='nid_photos/'),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='tour',
            name='tour_featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_featured_images/'),
        ),
        migrations.AddField(
            model_name='tourcategory',
            name='catalog_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backendApp.tour')),
            ],
        ),
    ]
