# Generated by Django 5.2.1 on 2025-08-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0008_city_catalog_image_country_catalog_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='guide',
        ),
        migrations.AddField(
            model_name='package',
            name='guides',
            field=models.ManyToManyField(blank=True, null=True, related_name='packages', to='backendApp.guideprofile'),
        ),
    ]
