# Generated by Django 5.2.1 on 2025-08-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0010_package_is_active_package_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='package_featured_images/'),
        ),
    ]
