# Generated by Django 5.2.1 on 2025-08-21 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0011_package_package_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
