# Generated by Django 5.2.1 on 2025-08-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0013_tourreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiderequestmodel',
            name='achievements',
            field=models.TextField(blank=True, help_text='Comma-separated list of achievements', null=True),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certification_images/')),
                ('guide_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='backendApp.guiderequestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='GuideAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='backendApp.guideprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuideCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chr_image', models.ImageField(blank=True, null=True, upload_to='certification_images/')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='backendApp.guideprofile')),
            ],
        ),
        migrations.CreateModel(
            name='GuideSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='backendApp.guideprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('guide_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialties', to='backendApp.guiderequestmodel')),
            ],
        ),
    ]
