# Generated by Django 5.2.1 on 2025-08-22 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0014_guiderequestmodel_achievements_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialty',
            name='guide_request',
        ),
        migrations.RemoveField(
            model_name='guiderequestmodel',
            name='achievements',
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='fb_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='specialties',
            field=models.TextField(blank=True, help_text='Comma-separated list of specialties', null=True),
        ),
        migrations.AddField(
            model_name='guiderequestmodel',
            name='Specialties',
            field=models.TextField(blank=True, help_text='Comma-separated list of specialties', null=True),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('guide_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='backendApp.guiderequestmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='GuideSpecialty',
        ),
        migrations.DeleteModel(
            name='Specialty',
        ),
    ]
