# Generated by Django 5.2.1 on 2025-08-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0015_remove_specialty_guide_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guiderequestmodel',
            old_name='Specialties',
            new_name='specialties',
        ),
    ]
