# Generated by Django 5.2.3 on 2025-06-25 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_customuser_maritalstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='relationshipStatus',
            new_name='fullName',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='mobile',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='profileimage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='maritalStatus',
        ),
        migrations.AddField(
            model_name='customuser',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobileNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='permanentAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='presentAddress',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
