# Generated by Django 5.2.3 on 2025-06-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_customuser_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileimage',
            field=models.ImageField(null=True, upload_to='static/photo'),
        ),
    ]
