# Generated by Django 5.2.3 on 2025-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=100)),
                ('description', models.TextField(max_length=100, null=100)),
                ('dueDate', models.DateField(auto_now=True, null=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'InProgress'), ('Completed', 'Completed')], max_length=100, null=True)),
            ],
        ),
    ]
