# Generated by Django 5.2.3 on 2025-07-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoApp', '0002_todomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('inProgress', 'InProgress'), ('completed', 'Completed')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todomodel',
            name='updated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
