# Generated by Django 5.2.4 on 2025-07-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('about_company', models.CharField(max_length=100, null=True)),
                ('company_logo', models.ImageField(null=True, upload_to='midea/image')),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('requirements', models.CharField(max_length=100, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('job_type', models.CharField(choices=[('Full_Time', 'Full_Time'), ('Remote', 'Remote'), ('Internship', 'Internship')], max_length=100, null=True)),
            ],
        ),
    ]
