# Generated by Django 5.2.3 on 2025-07-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0005_alter_customusermodel_studentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmodel",
            name="createAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmodel",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectmodel",
            name="projectStatus",
            field=models.CharField(
                choices=[
                    ("NotStarted", "Not Started"),
                    ("InProgress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="NotStarted",
                max_length=20,
                null=True,
            ),
        ),
    ]
