# Generated by Django 5.2.3 on 2025-06-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('ingredients', models.CharField()),
                ('instructions', models.CharField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
