# Generated by Django 5.2.3 on 2025-07-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectApp", "0004_rename_fullname_customusermodel_studentname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customusermodel",
            name="studentId",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
