# Generated by Django 5.2.4 on 2025-07-12 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authApp', '0002_studentpendingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='courseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(max_length=100, null=True)),
                ('courseDescription', models.TextField(null=True)),
                ('courseDuration', models.IntegerField(null=True)),
                ('courseStartDate', models.DateField(null=True)),
                ('courseFee', models.IntegerField(null=True)),
                ('assignTeacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.teachermodel')),
            ],
        ),
        migrations.CreateModel(
            name='admittedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.IntegerField(null=True)),
                ('due', models.IntegerField(null=True)),
                ('admittedDate', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.studentmodel')),
                ('admittedCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.coursemodel')),
            ],
        ),
    ]
