# Generated by Django 5.2.3 on 2025-07-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/photo'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='dueDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
