# Generated by Django 5.2.4 on 2025-07-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='pendingStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accept', 'Accept'), ('Rejected', 'Rejected')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pendingaccountmodel',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pendingaccountmodel',
            name='userTypes',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Candidate', 'Candidate')], max_length=100, null=True),
        ),
    ]
