# Generated by Django 5.2.3 on 2025-06-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Panding'), ('in_prograss', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('due_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
