# Generated by Django 5.2.3 on 2025-06-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('student_image', models.ImageField(upload_to='Media/Photo')),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
