# Generated by Django 5.2.3 on 2025-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('BookCategory', models.CharField(max_length=100)),
                ('PublishDate', models.DateField()),
                ('Description', models.TextField()),
            ],
        ),
    ]
