# Generated by Django 5.2.4 on 2025-07-19 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofilemodel',
            name='employer_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='emplayer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employer_app.employerprofilemodel'),
        ),
    ]
