# Generated by Django 5.2.4 on 2025-07-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admittedmodel',
            name='due',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admittedmodel',
            name='payment',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='courseDuration',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='courseFee',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
